use hotkeyd_derive::{ConfigKebabCase, EnumIndex};
use rdev::Key as RDevKey;

#[derive(Debug)]
pub enum Key {
    Modifier(ModifierKey),
    Keyboard(KeyboardKey),
}

impl Key {
    pub fn new_from_rdev(key: RDevKey) -> Self {
        match key {
            // modifier keys
            RDevKey::ShiftRight => Self::Modifier(ModifierKey::ShiftRight),
            RDevKey::AltGr => Self::Modifier(ModifierKey::AltGr),
            RDevKey::MetaRight => Self::Modifier(ModifierKey::MetaRight),
            RDevKey::MetaLeft => Self::Modifier(ModifierKey::MetaLeft),
            RDevKey::Alt => Self::Modifier(ModifierKey::Alt),
            RDevKey::ControlLeft => Self::Modifier(ModifierKey::ControlLeft),
            RDevKey::ControlRight => Self::Modifier(ModifierKey::ControlRight),
            RDevKey::Function => Self::Modifier(ModifierKey::Function),
            RDevKey::ShiftLeft => Self::Modifier(ModifierKey::ShiftLeft),
            RDevKey::CapsLock => Self::Modifier(ModifierKey::CapsLock),

            // keyboard keys
            RDevKey::Backspace => Self::Keyboard(KeyboardKey::Backspace),
            RDevKey::Delete => Self::Keyboard(KeyboardKey::Delete),
            RDevKey::DownArrow => Self::Keyboard(KeyboardKey::DownArrow),
            RDevKey::End => Self::Keyboard(KeyboardKey::End),
            RDevKey::Escape => Self::Keyboard(KeyboardKey::Escape),
            RDevKey::F1 => Self::Keyboard(KeyboardKey::F1),
            RDevKey::F10 => Self::Keyboard(KeyboardKey::F10),
            RDevKey::F11 => Self::Keyboard(KeyboardKey::F11),
            RDevKey::F12 => Self::Keyboard(KeyboardKey::F12),
            RDevKey::F2 => Self::Keyboard(KeyboardKey::F2),
            RDevKey::F3 => Self::Keyboard(KeyboardKey::F3),
            RDevKey::F4 => Self::Keyboard(KeyboardKey::F4),
            RDevKey::F5 => Self::Keyboard(KeyboardKey::F5),
            RDevKey::F6 => Self::Keyboard(KeyboardKey::F6),
            RDevKey::F7 => Self::Keyboard(KeyboardKey::F7),
            RDevKey::F8 => Self::Keyboard(KeyboardKey::F8),
            RDevKey::F9 => Self::Keyboard(KeyboardKey::F9),
            RDevKey::Home => Self::Keyboard(KeyboardKey::Home),
            RDevKey::LeftArrow => Self::Keyboard(KeyboardKey::LeftArrow),
            RDevKey::PageDown => Self::Keyboard(KeyboardKey::PageDown),
            RDevKey::PageUp => Self::Keyboard(KeyboardKey::PageUp),
            RDevKey::Return => Self::Keyboard(KeyboardKey::Return),
            RDevKey::RightArrow => Self::Keyboard(KeyboardKey::RightArrow),
            RDevKey::Space => Self::Keyboard(KeyboardKey::Space),
            RDevKey::Tab => Self::Keyboard(KeyboardKey::Tab),
            RDevKey::UpArrow => Self::Keyboard(KeyboardKey::UpArrow),
            RDevKey::PrintScreen => Self::Keyboard(KeyboardKey::PrintScreen),
            RDevKey::ScrollLock => Self::Keyboard(KeyboardKey::ScrollLock),
            RDevKey::Pause => Self::Keyboard(KeyboardKey::Pause),
            RDevKey::NumLock => Self::Keyboard(KeyboardKey::NumLock),
            RDevKey::BackQuote => Self::Keyboard(KeyboardKey::BackQuote),
            RDevKey::Num1 => Self::Keyboard(KeyboardKey::Num1),
            RDevKey::Num2 => Self::Keyboard(KeyboardKey::Num2),
            RDevKey::Num3 => Self::Keyboard(KeyboardKey::Num3),
            RDevKey::Num4 => Self::Keyboard(KeyboardKey::Num4),
            RDevKey::Num5 => Self::Keyboard(KeyboardKey::Num5),
            RDevKey::Num6 => Self::Keyboard(KeyboardKey::Num6),
            RDevKey::Num7 => Self::Keyboard(KeyboardKey::Num7),
            RDevKey::Num8 => Self::Keyboard(KeyboardKey::Num8),
            RDevKey::Num9 => Self::Keyboard(KeyboardKey::Num9),
            RDevKey::Num0 => Self::Keyboard(KeyboardKey::Num0),
            RDevKey::Minus => Self::Keyboard(KeyboardKey::Minus),
            RDevKey::Equal => Self::Keyboard(KeyboardKey::Equal),
            RDevKey::KeyQ => Self::Keyboard(KeyboardKey::KeyQ),
            RDevKey::KeyW => Self::Keyboard(KeyboardKey::KeyW),
            RDevKey::KeyE => Self::Keyboard(KeyboardKey::KeyE),
            RDevKey::KeyR => Self::Keyboard(KeyboardKey::KeyR),
            RDevKey::KeyT => Self::Keyboard(KeyboardKey::KeyT),
            RDevKey::KeyY => Self::Keyboard(KeyboardKey::KeyY),
            RDevKey::KeyU => Self::Keyboard(KeyboardKey::KeyU),
            RDevKey::KeyI => Self::Keyboard(KeyboardKey::KeyI),
            RDevKey::KeyO => Self::Keyboard(KeyboardKey::KeyO),
            RDevKey::KeyP => Self::Keyboard(KeyboardKey::KeyP),
            RDevKey::LeftBracket => Self::Keyboard(KeyboardKey::LeftBracket),
            RDevKey::RightBracket => Self::Keyboard(KeyboardKey::RightBracket),
            RDevKey::KeyA => Self::Keyboard(KeyboardKey::KeyA),
            RDevKey::KeyS => Self::Keyboard(KeyboardKey::KeyS),
            RDevKey::KeyD => Self::Keyboard(KeyboardKey::KeyD),
            RDevKey::KeyF => Self::Keyboard(KeyboardKey::KeyF),
            RDevKey::KeyG => Self::Keyboard(KeyboardKey::KeyG),
            RDevKey::KeyH => Self::Keyboard(KeyboardKey::KeyH),
            RDevKey::KeyJ => Self::Keyboard(KeyboardKey::KeyJ),
            RDevKey::KeyK => Self::Keyboard(KeyboardKey::KeyK),
            RDevKey::KeyL => Self::Keyboard(KeyboardKey::KeyL),
            RDevKey::SemiColon => Self::Keyboard(KeyboardKey::SemiColon),
            RDevKey::Quote => Self::Keyboard(KeyboardKey::Quote),
            RDevKey::BackSlash => Self::Keyboard(KeyboardKey::BackSlash),
            RDevKey::IntlBackslash => Self::Keyboard(KeyboardKey::IntlBackslash),
            RDevKey::KeyZ => Self::Keyboard(KeyboardKey::KeyZ),
            RDevKey::KeyX => Self::Keyboard(KeyboardKey::KeyX),
            RDevKey::KeyC => Self::Keyboard(KeyboardKey::KeyC),
            RDevKey::KeyV => Self::Keyboard(KeyboardKey::KeyV),
            RDevKey::KeyB => Self::Keyboard(KeyboardKey::KeyB),
            RDevKey::KeyN => Self::Keyboard(KeyboardKey::KeyN),
            RDevKey::KeyM => Self::Keyboard(KeyboardKey::KeyM),
            RDevKey::Comma => Self::Keyboard(KeyboardKey::Comma),
            RDevKey::Dot => Self::Keyboard(KeyboardKey::Dot),
            RDevKey::Slash => Self::Keyboard(KeyboardKey::Slash),
            RDevKey::Insert => Self::Keyboard(KeyboardKey::Insert),
            RDevKey::KpReturn => Self::Keyboard(KeyboardKey::KpReturn),
            RDevKey::KpMinus => Self::Keyboard(KeyboardKey::KpMinus),
            RDevKey::KpPlus => Self::Keyboard(KeyboardKey::KpPlus),
            RDevKey::KpMultiply => Self::Keyboard(KeyboardKey::KpMultiply),
            RDevKey::KpDivide => Self::Keyboard(KeyboardKey::KpDivide),
            RDevKey::Kp0 => Self::Keyboard(KeyboardKey::Kp0),
            RDevKey::Kp1 => Self::Keyboard(KeyboardKey::Kp1),
            RDevKey::Kp2 => Self::Keyboard(KeyboardKey::Kp2),
            RDevKey::Kp3 => Self::Keyboard(KeyboardKey::Kp3),
            RDevKey::Kp4 => Self::Keyboard(KeyboardKey::Kp4),
            RDevKey::Kp5 => Self::Keyboard(KeyboardKey::Kp5),
            RDevKey::Kp6 => Self::Keyboard(KeyboardKey::Kp6),
            RDevKey::Kp7 => Self::Keyboard(KeyboardKey::Kp7),
            RDevKey::Kp8 => Self::Keyboard(KeyboardKey::Kp8),
            RDevKey::Kp9 => Self::Keyboard(KeyboardKey::Kp9),
            RDevKey::KpDelete => Self::Keyboard(KeyboardKey::KpDelete),
            RDevKey::Unknown(code) => Self::Keyboard(KeyboardKey::Unknown(code)),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIndex, PartialOrd, Ord, Hash, ConfigKebabCase)]
pub enum ModifierKey {
    ShiftLeft,
    ShiftRight,
    MetaRight,
    MetaLeft,
    ControlLeft,
    ControlRight,
    AltGr,
    Alt,
    Function,
    CapsLock,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIndex, PartialOrd, Ord, Hash, ConfigKebabCase)]
pub enum KeyboardKey {
    Backspace,
    Delete,
    DownArrow,
    End,
    Escape,
    F1,
    F10,
    F11,
    F12,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    Home,
    LeftArrow,
    PageDown,
    PageUp,
    Return,
    RightArrow,
    Space,
    Tab,
    UpArrow,
    PrintScreen,
    ScrollLock,
    Pause,
    NumLock,
    BackQuote,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Num0,
    Minus,
    Equal,
    KeyQ,
    KeyW,
    KeyE,
    KeyR,
    KeyT,
    KeyY,
    KeyU,
    KeyI,
    KeyO,
    KeyP,
    LeftBracket,
    RightBracket,
    KeyA,
    KeyS,
    KeyD,
    KeyF,
    KeyG,
    KeyH,
    KeyJ,
    KeyK,
    KeyL,
    SemiColon,
    Quote,
    BackSlash,
    IntlBackslash,
    KeyZ,
    KeyX,
    KeyC,
    KeyV,
    KeyB,
    KeyN,
    KeyM,
    Comma,
    Dot,
    Slash,
    Insert,
    KpReturn,
    KpMinus,
    KpPlus,
    KpMultiply,
    KpDivide,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDelete,
    Unknown(u32),
}
