use hotkeyd_derive::{ConfigKebabCase, EnumIndex};
use rdev::{Button, Key as RDevKey};

#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIndex, PartialOrd, Ord, Hash, ConfigKebabCase)]
pub enum Key {
    // keys
    Alt,
    AltGr,
    Backspace,
    CapsLock,
    ControlLeft,
    ControlRight,
    Delete,
    DownArrow,
    End,
    Escape,
    F1,
    F10,
    F11,
    F12,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    Home,
    LeftArrow,
    MetaLeft,
    MetaRight,
    PageDown,
    PageUp,
    Return,
    RightArrow,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    UpArrow,
    PrintScreen,
    ScrollLock,
    Pause,
    NumLock,
    BackQuote,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Num0,
    Minus,
    Equal,
    KeyQ,
    KeyW,
    KeyE,
    KeyR,
    KeyT,
    KeyY,
    KeyU,
    KeyI,
    KeyO,
    KeyP,
    LeftBracket,
    RightBracket,
    KeyA,
    KeyS,
    KeyD,
    KeyF,
    KeyG,
    KeyH,
    KeyJ,
    KeyK,
    KeyL,
    SemiColon,
    Quote,
    BackSlash,
    IntlBackslash,
    KeyZ,
    KeyX,
    KeyC,
    KeyV,
    KeyB,
    KeyN,
    KeyM,
    Comma,
    Dot,
    Slash,
    Insert,
    KpReturn,
    KpMinus,
    KpPlus,
    KpMultiply,
    KpDivide,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDelete,
    Function,
    UnknownKey(u32),

    // buttons
    Left,
    Right,
    Middle,
    UnknownButton(u8)
}

impl Key {
    pub fn new_from_rdev_button(button: Button) -> Self {
        match button {
            Button::Left => Key::Left,
            Button::Right => Key::Right,
            Button::Middle => Key::Middle,
            Button::Unknown(u) => Key::UnknownButton(u)
        }
    }

    pub fn new_from_rdev_key(key: RDevKey) -> Self {
        match key {
            RDevKey::Alt => Key::Alt,
            RDevKey::AltGr => Key::AltGr,
            RDevKey::Backspace => Key::Backspace,
            RDevKey::CapsLock => Key::CapsLock,
            RDevKey::ControlLeft => Key::ControlLeft,
            RDevKey::ControlRight => Key::ControlRight,
            RDevKey::Delete => Key::Delete,
            RDevKey::DownArrow => Key::DownArrow,
            RDevKey::End => Key::End,
            RDevKey::Escape => Key::Escape,
            RDevKey::F1 => Key::F1,
            RDevKey::F10 => Key::F10,
            RDevKey::F11 => Key::F11,
            RDevKey::F12 => Key::F12,
            RDevKey::F2 => Key::F2,
            RDevKey::F3 => Key::F3,
            RDevKey::F4 => Key::F4,
            RDevKey::F5 => Key::F5,
            RDevKey::F6 => Key::F6,
            RDevKey::F7 => Key::F7,
            RDevKey::F8 => Key::F8,
            RDevKey::F9 => Key::F9,
            RDevKey::Home => Key::Home,
            RDevKey::LeftArrow => Key::LeftArrow,
            RDevKey::MetaLeft => Key::MetaLeft,
            RDevKey::MetaRight => Key::MetaRight,
            RDevKey::PageDown => Key::PageDown,
            RDevKey::PageUp => Key::PageUp,
            RDevKey::Return => Key::Return,
            RDevKey::RightArrow => Key::RightArrow,
            RDevKey::ShiftLeft => Key::ShiftLeft,
            RDevKey::ShiftRight => Key::ShiftRight,
            RDevKey::Space => Key::Space,
            RDevKey::Tab => Key::Tab,
            RDevKey::UpArrow => Key::UpArrow,
            RDevKey::PrintScreen => Key::PrintScreen,
            RDevKey::ScrollLock => Key::ScrollLock,
            RDevKey::Pause => Key::Pause,
            RDevKey::NumLock => Key::NumLock,
            RDevKey::BackQuote => Key::BackQuote,
            RDevKey::Num1 => Key::Num1,
            RDevKey::Num2 => Key::Num2,
            RDevKey::Num3 => Key::Num3,
            RDevKey::Num4 => Key::Num4,
            RDevKey::Num5 => Key::Num5,
            RDevKey::Num6 => Key::Num6,
            RDevKey::Num7 => Key::Num7,
            RDevKey::Num8 => Key::Num8,
            RDevKey::Num9 => Key::Num9,
            RDevKey::Num0 => Key::Num0,
            RDevKey::Minus => Key::Minus,
            RDevKey::Equal => Key::Equal,
            RDevKey::KeyQ => Key::KeyQ,
            RDevKey::KeyW => Key::KeyW,
            RDevKey::KeyE => Key::KeyE,
            RDevKey::KeyR => Key::KeyR,
            RDevKey::KeyT => Key::KeyT,
            RDevKey::KeyY => Key::KeyY,
            RDevKey::KeyU => Key::KeyU,
            RDevKey::KeyI => Key::KeyI,
            RDevKey::KeyO => Key::KeyO,
            RDevKey::KeyP => Key::KeyP,
            RDevKey::LeftBracket => Key::LeftBracket,
            RDevKey::RightBracket => Key::RightBracket,
            RDevKey::KeyA => Key::KeyA,
            RDevKey::KeyS => Key::KeyS,
            RDevKey::KeyD => Key::KeyD,
            RDevKey::KeyF => Key::KeyF,
            RDevKey::KeyG => Key::KeyG,
            RDevKey::KeyH => Key::KeyH,
            RDevKey::KeyJ => Key::KeyJ,
            RDevKey::KeyK => Key::KeyK,
            RDevKey::KeyL => Key::KeyL,
            RDevKey::SemiColon => Key::SemiColon,
            RDevKey::Quote => Key::Quote,
            RDevKey::BackSlash => Key::BackSlash,
            RDevKey::IntlBackslash => Key::IntlBackslash,
            RDevKey::KeyZ => Key::KeyZ,
            RDevKey::KeyX => Key::KeyX,
            RDevKey::KeyC => Key::KeyC,
            RDevKey::KeyV => Key::KeyV,
            RDevKey::KeyB => Key::KeyB,
            RDevKey::KeyN => Key::KeyN,
            RDevKey::KeyM => Key::KeyM,
            RDevKey::Comma => Key::Comma,
            RDevKey::Dot => Key::Dot,
            RDevKey::Slash => Key::Slash,
            RDevKey::Insert => Key::Insert,
            RDevKey::KpReturn => Key::KpReturn,
            RDevKey::KpMinus => Key::KpMinus,
            RDevKey::KpPlus => Key::KpPlus,
            RDevKey::KpMultiply => Key::KpMultiply,
            RDevKey::KpDivide => Key::KpDivide,
            RDevKey::Kp0 => Key::Kp0,
            RDevKey::Kp1 => Key::Kp1,
            RDevKey::Kp2 => Key::Kp2,
            RDevKey::Kp3 => Key::Kp3,
            RDevKey::Kp4 => Key::Kp4,
            RDevKey::Kp5 => Key::Kp5,
            RDevKey::Kp6 => Key::Kp6,
            RDevKey::Kp7 => Key::Kp7,
            RDevKey::Kp8 => Key::Kp8,
            RDevKey::Kp9 => Key::Kp9,
            RDevKey::KpDelete => Key::KpDelete,
            RDevKey::Function => Key::Function,
            RDevKey::Unknown(code) => Key::UnknownKey(code),
        }
    }
}

