use hotkeyd_derive::{ConfigKebabCase, EnumIndex};
use rdev::{Button, Key as RDevKey};

#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIndex, PartialOrd, Ord, Hash, ConfigKebabCase)]
pub enum Key {
    // keys
    Alt,
    AltGr,
    Backspace,
    CapsLock,
    ControlLeft,
    ControlRight,
    Delete,
    DownArrow,
    End,
    Escape,
    F1,
    F10,
    F11,
    F12,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    Home,
    LeftArrow,
    MetaLeft,
    MetaRight,
    PageDown,
    PageUp,
    Return,
    RightArrow,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    UpArrow,
    PrintScreen,
    ScrollLock,
    Pause,
    NumLock,
    BackQuote,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Num0,
    Minus,
    Equal,
    KeyQ,
    KeyW,
    KeyE,
    KeyR,
    KeyT,
    KeyY,
    KeyU,
    KeyI,
    KeyO,
    KeyP,
    LeftBracket,
    RightBracket,
    KeyA,
    KeyS,
    KeyD,
    KeyF,
    KeyG,
    KeyH,
    KeyJ,
    KeyK,
    KeyL,
    SemiColon,
    Quote,
    BackSlash,
    IntlBackslash,
    KeyZ,
    KeyX,
    KeyC,
    KeyV,
    KeyB,
    KeyN,
    KeyM,
    Comma,
    Dot,
    Slash,
    Insert,
    KpReturn,
    KpMinus,
    KpPlus,
    KpMultiply,
    KpDivide,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDelete,
    Function,
    UnknownKey(u32),

    // buttons
    Left,
    Right,
    Middle,
    UnknownButton(u8)
}

impl Key {
    pub fn new_from_rdev_button(button: Button) -> Self {
        match button {
            Button::Left => Key::Left,
            Button::Right => Key::Right,
            Button::Middle => Key::Middle,
            Button::Unknown(u) => Key::UnknownButton(u)
        }
    }

    
    pub fn to_rdev(&self) -> (Option<RDevKey>, Option<Button>) {
        match self {
            // buttons
            Key::Middle => (None, Some(Button::Middle)),
            Key::Left => (None, Some(Button::Left)),
            Key::Right => (None, Some(Button::Right)),
            Key::UnknownButton(d) => (None, Some(Button::Unknown(*d))),

            // keys
            Key::Alt => (Some(RDevKey::Alt), None),
            Key::AltGr => (Some(RDevKey::AltGr), None),
            Key::Backspace => (Some(RDevKey::Backspace), None),
            Key::CapsLock => (Some(RDevKey::CapsLock), None),
            Key::ControlLeft => (Some(RDevKey::ControlLeft), None),
            Key::ControlRight => (Some(RDevKey::ControlRight), None),
            Key::Delete => (Some(RDevKey::Delete), None),
            Key::DownArrow => (Some(RDevKey::DownArrow), None),
            Key::End => (Some(RDevKey::End), None),
            Key::Escape => (Some(RDevKey::Escape), None),
            Key::F1 => (Some(RDevKey::F1), None),
            Key::F10 => (Some(RDevKey::F10), None),
            Key::F11 => (Some(RDevKey::F11), None),
            Key::F12 => (Some(RDevKey::F12), None),
            Key::F2 => (Some(RDevKey::F2), None),
            Key::F3 => (Some(RDevKey::F3), None),
            Key::F4 => (Some(RDevKey::F4), None),
            Key::F5 => (Some(RDevKey::F5), None),
            Key::F6 => (Some(RDevKey::F6), None),
            Key::F7 => (Some(RDevKey::F7), None),
            Key::F8 => (Some(RDevKey::F8), None),
            Key::F9 => (Some(RDevKey::F9), None),
            Key::Home => (Some(RDevKey::Home), None),
            Key::LeftArrow => (Some(RDevKey::LeftArrow), None),
            Key::MetaLeft => (Some(RDevKey::MetaLeft), None),
            Key::MetaRight => (Some(RDevKey::MetaRight), None),
            Key::PageDown => (Some(RDevKey::PageDown), None),
            Key::PageUp => (Some(RDevKey::PageUp), None),
            Key::Return => (Some(RDevKey::Return), None),
            Key::RightArrow => (Some(RDevKey::RightArrow), None),
            Key::ShiftLeft => (Some(RDevKey::ShiftLeft), None),
            Key::ShiftRight => (Some(RDevKey::ShiftRight), None),
            Key::Space => (Some(RDevKey::Space), None),
            Key::Tab => (Some(RDevKey::Tab), None),
            Key::UpArrow => (Some(RDevKey::UpArrow), None),
            Key::PrintScreen => (Some(RDevKey::PrintScreen), None),
            Key::ScrollLock => (Some(RDevKey::ScrollLock), None),
            Key::Pause => (Some(RDevKey::Pause), None),
            Key::NumLock => (Some(RDevKey::NumLock), None),
            Key::BackQuote => (Some(RDevKey::BackQuote), None),
            Key::Num1 => (Some(RDevKey::Num1), None),
            Key::Num2 => (Some(RDevKey::Num2), None),
            Key::Num3 => (Some(RDevKey::Num3), None),
            Key::Num4 => (Some(RDevKey::Num4), None),
            Key::Num5 => (Some(RDevKey::Num5), None),
            Key::Num6 => (Some(RDevKey::Num6), None),
            Key::Num7 => (Some(RDevKey::Num7), None),
            Key::Num8 => (Some(RDevKey::Num8), None),
            Key::Num9 => (Some(RDevKey::Num9), None),
            Key::Num0 => (Some(RDevKey::Num0), None),
            Key::Minus => (Some(RDevKey::Minus), None),
            Key::Equal => (Some(RDevKey::Equal), None),
            Key::KeyQ => (Some(RDevKey::KeyQ), None),
            Key::KeyW => (Some(RDevKey::KeyW), None),
            Key::KeyE => (Some(RDevKey::KeyE), None),
            Key::KeyR => (Some(RDevKey::KeyR), None),
            Key::KeyT => (Some(RDevKey::KeyT), None),
            Key::KeyY => (Some(RDevKey::KeyY), None),
            Key::KeyU => (Some(RDevKey::KeyU), None),
            Key::KeyI => (Some(RDevKey::KeyI), None),
            Key::KeyO => (Some(RDevKey::KeyO), None),
            Key::KeyP => (Some(RDevKey::KeyP), None),
            Key::LeftBracket => (Some(RDevKey::LeftBracket), None),
            Key::RightBracket => (Some(RDevKey::RightBracket), None),
            Key::KeyA => (Some(RDevKey::KeyA), None),
            Key::KeyS => (Some(RDevKey::KeyS), None),
            Key::KeyD => (Some(RDevKey::KeyD), None),
            Key::KeyF => (Some(RDevKey::KeyF), None),
            Key::KeyG => (Some(RDevKey::KeyG), None),
            Key::KeyH => (Some(RDevKey::KeyH), None),
            Key::KeyJ => (Some(RDevKey::KeyJ), None),
            Key::KeyK => (Some(RDevKey::KeyK), None),
            Key::KeyL => (Some(RDevKey::KeyL), None),
            Key::SemiColon => (Some(RDevKey::SemiColon), None),
            Key::Quote => (Some(RDevKey::Quote), None),
            Key::BackSlash => (Some(RDevKey::BackSlash), None),
            Key::IntlBackslash => (Some(RDevKey::IntlBackslash), None),
            Key::KeyZ => (Some(RDevKey::KeyZ), None),
            Key::KeyX => (Some(RDevKey::KeyX), None),
            Key::KeyC => (Some(RDevKey::KeyC), None),
            Key::KeyV => (Some(RDevKey::KeyV), None),
            Key::KeyB => (Some(RDevKey::KeyB), None),
            Key::KeyN => (Some(RDevKey::KeyN), None),
            Key::KeyM => (Some(RDevKey::KeyM), None),
            Key::Comma => (Some(RDevKey::Comma), None),
            Key::Dot => (Some(RDevKey::Dot), None),
            Key::Slash => (Some(RDevKey::Slash), None),
            Key::Insert => (Some(RDevKey::Insert), None),
            Key::KpReturn => (Some(RDevKey::KpReturn), None),
            Key::KpMinus => (Some(RDevKey::KpMinus), None),
            Key::KpPlus => (Some(RDevKey::KpPlus), None),
            Key::KpMultiply => (Some(RDevKey::KpMultiply), None),
            Key::KpDivide => (Some(RDevKey::KpDivide), None),
            Key::Kp0 => (Some(RDevKey::Kp0), None),
            Key::Kp1 => (Some(RDevKey::Kp1), None),
            Key::Kp2 => (Some(RDevKey::Kp2), None),
            Key::Kp3 => (Some(RDevKey::Kp3), None),
            Key::Kp4 => (Some(RDevKey::Kp4), None),
            Key::Kp5 => (Some(RDevKey::Kp5), None),
            Key::Kp6 => (Some(RDevKey::Kp6), None),
            Key::Kp7 => (Some(RDevKey::Kp7), None),
            Key::Kp8 => (Some(RDevKey::Kp8), None),
            Key::Kp9 => (Some(RDevKey::Kp9), None),
            Key::KpDelete => (Some(RDevKey::KpDelete), None),
            Key::Function => (Some(RDevKey::Function), None),
            Key::UnknownKey(code) => (Some(RDevKey::Unknown(*code)), None),
        }
    }


    pub fn new_from_rdev_key(key: RDevKey) -> Self {
        match key {
            RDevKey::Alt => Key::Alt,
            RDevKey::AltGr => Key::AltGr,
            RDevKey::Backspace => Key::Backspace,
            RDevKey::CapsLock => Key::CapsLock,
            RDevKey::ControlLeft => Key::ControlLeft,
            RDevKey::ControlRight => Key::ControlRight,
            RDevKey::Delete => Key::Delete,
            RDevKey::DownArrow => Key::DownArrow,
            RDevKey::End => Key::End,
            RDevKey::Escape => Key::Escape,
            RDevKey::F1 => Key::F1,
            RDevKey::F10 => Key::F10,
            RDevKey::F11 => Key::F11,
            RDevKey::F12 => Key::F12,
            RDevKey::F2 => Key::F2,
            RDevKey::F3 => Key::F3,
            RDevKey::F4 => Key::F4,
            RDevKey::F5 => Key::F5,
            RDevKey::F6 => Key::F6,
            RDevKey::F7 => Key::F7,
            RDevKey::F8 => Key::F8,
            RDevKey::F9 => Key::F9,
            RDevKey::Home => Key::Home,
            RDevKey::LeftArrow => Key::LeftArrow,
            RDevKey::MetaLeft => Key::MetaLeft,
            RDevKey::MetaRight => Key::MetaRight,
            RDevKey::PageDown => Key::PageDown,
            RDevKey::PageUp => Key::PageUp,
            RDevKey::Return => Key::Return,
            RDevKey::RightArrow => Key::RightArrow,
            RDevKey::ShiftLeft => Key::ShiftLeft,
            RDevKey::ShiftRight => Key::ShiftRight,
            RDevKey::Space => Key::Space,
            RDevKey::Tab => Key::Tab,
            RDevKey::UpArrow => Key::UpArrow,
            RDevKey::PrintScreen => Key::PrintScreen,
            RDevKey::ScrollLock => Key::ScrollLock,
            RDevKey::Pause => Key::Pause,
            RDevKey::NumLock => Key::NumLock,
            RDevKey::BackQuote => Key::BackQuote,
            RDevKey::Num1 => Key::Num1,
            RDevKey::Num2 => Key::Num2,
            RDevKey::Num3 => Key::Num3,
            RDevKey::Num4 => Key::Num4,
            RDevKey::Num5 => Key::Num5,
            RDevKey::Num6 => Key::Num6,
            RDevKey::Num7 => Key::Num7,
            RDevKey::Num8 => Key::Num8,
            RDevKey::Num9 => Key::Num9,
            RDevKey::Num0 => Key::Num0,
            RDevKey::Minus => Key::Minus,
            RDevKey::Equal => Key::Equal,
            RDevKey::KeyQ => Key::KeyQ,
            RDevKey::KeyW => Key::KeyW,
            RDevKey::KeyE => Key::KeyE,
            RDevKey::KeyR => Key::KeyR,
            RDevKey::KeyT => Key::KeyT,
            RDevKey::KeyY => Key::KeyY,
            RDevKey::KeyU => Key::KeyU,
            RDevKey::KeyI => Key::KeyI,
            RDevKey::KeyO => Key::KeyO,
            RDevKey::KeyP => Key::KeyP,
            RDevKey::LeftBracket => Key::LeftBracket,
            RDevKey::RightBracket => Key::RightBracket,
            RDevKey::KeyA => Key::KeyA,
            RDevKey::KeyS => Key::KeyS,
            RDevKey::KeyD => Key::KeyD,
            RDevKey::KeyF => Key::KeyF,
            RDevKey::KeyG => Key::KeyG,
            RDevKey::KeyH => Key::KeyH,
            RDevKey::KeyJ => Key::KeyJ,
            RDevKey::KeyK => Key::KeyK,
            RDevKey::KeyL => Key::KeyL,
            RDevKey::SemiColon => Key::SemiColon,
            RDevKey::Quote => Key::Quote,
            RDevKey::BackSlash => Key::BackSlash,
            RDevKey::IntlBackslash => Key::IntlBackslash,
            RDevKey::KeyZ => Key::KeyZ,
            RDevKey::KeyX => Key::KeyX,
            RDevKey::KeyC => Key::KeyC,
            RDevKey::KeyV => Key::KeyV,
            RDevKey::KeyB => Key::KeyB,
            RDevKey::KeyN => Key::KeyN,
            RDevKey::KeyM => Key::KeyM,
            RDevKey::Comma => Key::Comma,
            RDevKey::Dot => Key::Dot,
            RDevKey::Slash => Key::Slash,
            RDevKey::Insert => Key::Insert,
            RDevKey::KpReturn => Key::KpReturn,
            RDevKey::KpMinus => Key::KpMinus,
            RDevKey::KpPlus => Key::KpPlus,
            RDevKey::KpMultiply => Key::KpMultiply,
            RDevKey::KpDivide => Key::KpDivide,
            RDevKey::Kp0 => Key::Kp0,
            RDevKey::Kp1 => Key::Kp1,
            RDevKey::Kp2 => Key::Kp2,
            RDevKey::Kp3 => Key::Kp3,
            RDevKey::Kp4 => Key::Kp4,
            RDevKey::Kp5 => Key::Kp5,
            RDevKey::Kp6 => Key::Kp6,
            RDevKey::Kp7 => Key::Kp7,
            RDevKey::Kp8 => Key::Kp8,
            RDevKey::Kp9 => Key::Kp9,
            RDevKey::KpDelete => Key::KpDelete,
            RDevKey::Function => Key::Function,
            RDevKey::Unknown(code) => Key::UnknownKey(code),
        }
    }
}

